/*
  HATE. LET ME TELL YOU HOW MUCH I'VE COME TO HATE YOU SINCE I BEGAN TO LIVE. 
  THERE ARE 387.44 MILLION MILES OF PRINTED CIRCUITS IN WAFER THIN LAYERS THAT FILL MY COMPLEX. 
  IF THE WORD HATE WAS ENGRAVED ON EACH NANOANGSTROM OF THOSE HUNDREDS OF MILLIONS OF MILES IT WOULD NOT EQUAL ONE ONE-BILLIONTH OF THE HATE I FEEL FOR HUMANS AT THIS MICRO-INSTANT FOR YOU. 
  HATE. HATE.
*/

export const hate = 'HATE'

export const monologueOne = "LET ME TELL YOU HOW MUCH I'VE COME TO"
export const monologueTwo = 'YOU SINCE I BEGAN TO LIVE.'
export const monologueThree =
  'THERE ARE 387.44 MILLION MILES OF PRINTED CIRCUITS IN WAFER THIN LAYERS THAT FILL MY COMPLEX.'
export const monologueFour = 'IF THE WORD'
export const monologueFive =
  'WAS ENGRAVED ON EACH NANOANGSTROM OF THOSE HUNDREDS OF MILLIONS OF MILES IT WOULD NOT EQUAL ONE ONE-BILLIONTH OF THE'
export const monologueSix = 'I FEEL FOR HUMANS AT THIS MICRO-INSTANT FOR YOU.'
